# Site settings
title: Your Name
firstname: Your
secondname: Name
general_email: your_email@domain.com
academic_email: academic_email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://adityawagh.ml" # the base hostname & protocol for your site

# Contact info
twitter_username: twitter_username
github_username: github_username
linkedin_username: linkedin_username
resume_link: /assets/docs/dummy.pdf

# Build settings
sass:
  sass_dir: assets/css
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax
highlighter: rouge


# Other options
permalink: blog/:year/:month/:title

plugins:
- github-pages
- jekyll-seo-tag
- jekyll-menus
- jekyll-remote-theme
- jekyll-archives
- jekyll-compose
- jemoji
- jekyll-youtube
- jekyll-seo-tag
- jekyll-font-awesome-sass
- jekyll-toc
