# Site settings
title: Fabian Sato
firstname: Fabian
secondname: Sato
general_email: contacto@fabiansato.com


description: > # this means to ignore newlines until "baseurl:"
  Give a brief description of yourself, and maybe your passion/interests. It is displayed in search results.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://adityawagh.ml" # the base hostname & protocol for your site

# Contact info
twitter_username: https://twitter.com/codesato
github_username: https://github.com/fabiansato
linkedin_username: https://www.linkedin.com/in/fabian-gonzalez-481b2b19/
resume_link: /assets/docs/dummy.pdf

# Build settings
sass:
  sass_dir: assets/css
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax
highlighter: rouge


# Other options
permalink: blog/:year/:month/:title

plugins:
- github-pages
- jekyll-seo-tag
- jekyll-menus
- jekyll-remote-theme
- jekyll-archives
- jekyll-compose
- jemoji
- jekyll-youtube
- jekyll-seo-tag
- jekyll-font-awesome-sass
- jekyll-toc
