title: Adam Morgan
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Adam Morgan - Software Engineer and Designer
color_scheme: light
accent_color: blue
header:
  title: Adam
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Portfolio
      url: /portfolio/
      style: link
    - label: Training
      url: /training/
      style: link
    - label: Blog
      url: /blog/
      style: link
    # - label: Style Guide
    #   url: /style-guide/
    #   style: link
    - label: About
      url: /about/
      style: link
    - label: Contact
      url: /contact/
      style: link
footer:
  content: 'Adam Morgan'
  # links:
  #   - label: Made with Stackbit.
  #     url: 'https://www.stackbit.com'
  #     style: link
  #     new_window: true
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/atommorgan'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/adamjmorgan/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - label: Dribbble
      url: 'https://dribbble.com/atommorgan'
      style: icon
      icon_class: fa-dribbble
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/atommorgan/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 2
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
